### PR TITLE
Added Links section to footer

### PR DESCRIPTION
**Pull request by lightninq720**
This is currently untested so if it won't work please let me know and I will improve it. Otherwise, this should add a "Links" section to the footer which redirects to: the support server; the buymeacoffee link; the BWP Stats discord bot; and the BWP Stasts overlay

### CODE REVIEW

**Comment by VitroidFPV** [comment]
<details><summary>Comment has been resolved by Vit Semrad</summary>

screenshot

Needs a bit of margin between the two elements, will touch up
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 119.0.0.0 on Windows 10
Viewport:  1536 x 718 @1.25x
Language:  cs-CZ
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--voxyl-stats.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=119.0&resolution=1536x718&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2--voxyl-stats.netlify.app/) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=655bdecdb014c50008839ad0&commentID=655be214bd2a840098355e13&resolution=unresolved)

</details>

**Comment by VitroidFPV** [comment]
lgtm now

**Comment by lightninq720** [comment]
> lgtm now

I feel like there should be more of a divide between `Credits` and `Links` on the web

https://i.imgur.com/j5XzTf6.png

**Comment by lightninq720** [comment]
> > lgtm now
> 
> I feel like there should be more of a divide between `Credits` and `Links` on the web
> 
> https://i.imgur.com/j5XzTf6.png

Also seems like `Links:` is below `Credits:`: https://i.imgur.com/opoGFlF.png

**Pull request merged**
